#!/usr/bin/env bash
# Reconfigure nginx
sed  '/location \/hbnb_static/i location /number_odd_or_even { alias /data/web_static\;\n proxy_pass http://0.0.0.0:5001\;\n include proxy_params\; }' /etc/nginx/sites-enabled/default 
#sed -i 'try_files ' /etc/nginx/sites-available/default 
service nginx restart
